#!/bin/bash
#
# test simple command /bin/ls

command="exit 47"

# clean up
stop_shell

print_adv

# run command
`echo $command | $SHELL 2> /dev/null ; echo $? > $OUTPUTFILE` &

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
nmatch=`cat $OUTPUTFILE | grep -c "47"`
if [ $nmatch -eq 1 ]; then
	   print_ok
else
	   print_ko
fi

# clean up
stop_shell
